{
 "title": "STD Dashboard",
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "200ms",
 "panels": [
  {
   "title": "Speed",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 15, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "targets": [
    {
     "query": "from(bucket: \"haltech_data_std\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"0x370\")\n  |> filter(fn: (r) => r[\"position\"] == \"0-1\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Gear",
   "type": "timeseries",
   "description": "Current Gear",
   "gridPos": { "h": 5, "w": 7, "x": 16, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"haltech_data_std\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"0x470\")\n  |> filter(fn: (r) => r[\"position\"] == \"1\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Rotation Forces",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "query": "from(bucket: \"haltech_data_std\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"0x6F1\")\n  |> filter(fn: (r) => r[\"position\"] == \"0-1\" or r[\"position\"] == \"2-3\" or r[\"position\"] == \"4-5\" or r[\"position\"] == \"6-7\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "RPM",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "targets": [
    {
     "query": "from(bucket: \"haltech_data_std\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"0x360\")\n  |> filter(fn: (r) => r[\"position\"] == \"0-1\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Throttle Pedal Position",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "query": "from(bucket: \"haltech_data_std\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"0x471\")\n  |> filter(fn: (r) => r[\"position\"] == \"2-3\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Tyre Temps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "query": "from(bucket: \"haltech_data_std\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"0x6F1\")\n  |> filter(fn: (r) => r[\"position\"] == \"0-1\" or r[\"position\"] == \"2-3\" or r[\"position\"] == \"4-5\" or r[\"position\"] == \"6-7\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  }
 ]
}